### PR TITLE
Remove erroneous 'int' typehint from checkThrowable $expectedCode

### LINKED ISSUE #22: checkThrowable typing of expectedCode is wrong
The `$expectedCode` parameter of the `Asserts->checkThrowable` function is typed as `?int`, but this is incorrect, see https://www.php.net/manual/en/throwable.getcode.php ("Returns the exception code as int in Exception but possibly as other type in Exception descendants")

For this reason our tests now give type errors when trying to use module-asserts v2.

### PR DESCRIPTION
**Pull request by Venorcis**
Fixes #22

### CODE REVIEW

File: src/Codeception/Module/Asserts.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function expectThrowable($throwable, callable $callback): void
      * Check if the given throwable matches the expected data,
      * fail (throws an exception) if it does not.
      */
```
Comment (TavoNiievez) [inline src/Codeception/Module/Asserts.php:62]: please add a `@param` annotation to this method's docblock to indicate that this may be `int|Exception`.

**Review by TavoNiievez — CHANGES_REQUESTED** [review]

File: src/Codeception/Module/Asserts.php (hunk 1 above)
Comment (Venorcis) [inline src/Codeception/Module/Asserts.php:62]: @TavoNiievez your suggestion doesn't make sense to me, the code can be of literally any type (see https://www.php.net/manual/en/throwable.getcode.php)

**Review by TavoNiievez — APPROVED** [review]

**Comment by TavoNiievez** [comment]
@Venorcis Thank you
